AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SpringBoot API with the aws-serverless-java-container library

#Globals:
#  Api:
#    # API Gateway regional endpoints
#    EndpointConfiguration: REGIONAL

Resources:
  CoreApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.javabrown.api.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/api-lambda-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringBootCoreApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/country'
    Export:
      Name: SpringBootCoreApi